/* The following code was generated by JFlex 1.4.3 on 2013-04-01 22:36 */

package com.raket.silverstripe;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.raket.silverstripe.psi.SilverStripeTypes;
import com.raket.silverstripe.psi.SilverStripeTokenType;
import com.intellij.psi.TokenType;
import com.intellij.psi.*;
import com.intellij.psi.xml.*;
import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.intellij.util.containers.Stack;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 2013-04-01 22:36 from the specification file
 * <tt>C:/IdeaProjects/idea-silverstripe/src/com/raket/silverstripe/SilverStripe.flex</tt>
 */
public class SilverStripeLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int SS_VAR = 2;
  public static final int SS_TRANSLATION = 16;
  public static final int SS_BLOCK_VAR = 8;
  public static final int SS_BLOCK_START = 6;
  public static final int SS_BAD_VAR = 10;
  public static final int SS_BAD_BLOCK_STATEMENT = 12;
  public static final int SS_INCLUDE_STATEMENT = 20;
  public static final int YYINITIAL = 0;
  public static final int SS_IF_STATEMENT = 18;
  public static final int SS_WITH_DELIMITER = 4;
  public static final int SS_COMMENT = 14;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9,  9, 10, 10
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\1\0\1\3\1\2\22\0\1\3\1\4\1\10"+
    "\1\0\1\5\1\17\1\40\1\11\1\7\1\12\3\0\1\47\1\13"+
    "\13\0\1\0\1\0\1\16\1\37\1\20\2\0\32\6\1\0\1\0"+
    "\2\0\1\36\1\0\1\43\1\42\1\30\1\46\1\34\1\33\1\44"+
    "\1\27\1\25\2\6\1\21\1\6\1\31\1\22\1\23\1\6\1\32"+
    "\1\35\1\26\1\45\1\6\1\24\3\6\1\14\1\41\1\15\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\12\0\3\1\1\2\2\3\1\4\1\2\1\5"+
    "\1\2\1\6\2\7\1\10\10\7\1\11\1\2\1\12"+
    "\3\2\2\3\1\4\2\2\2\3\1\4\2\2\2\3"+
    "\1\4\1\2\1\13\2\2\1\14\2\2\1\14\1\15"+
    "\2\2\1\16\1\17\1\20\1\21\1\22\1\23\3\0"+
    "\1\24\10\0\1\25\5\0\1\26\1\15\2\0\1\27"+
    "\1\0\1\14\1\30\2\0\1\31\16\0\1\15\4\0"+
    "\1\32\1\33\2\0\1\34\3\0\1\35\1\36\20\0"+
    "\1\37\2\0\1\40\1\41\5\0\1\42\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0230"+
    "\0\u0258\0\u0280\0\u02a8\0\u0230\0\u02d0\0\u0230\0\u0230\0\u0258"+
    "\0\u02f8\0\u0320\0\u0348\0\u0370\0\u0398\0\u03c0\0\u03e8\0\u0410"+
    "\0\u0438\0\u0460\0\u0488\0\u04b0\0\u0348\0\u04d8\0\u0500\0\u0500"+
    "\0\u0528\0\u0550\0\u0578\0\u05a0\0\u05a0\0\u05c8\0\u05f0\0\u0618"+
    "\0\u0640\0\u0640\0\u0668\0\u0690\0\u06b8\0\u06e0\0\u0708\0\u0730"+
    "\0\u0758\0\u0780\0\u07a8\0\u07d0\0\u0708\0\u07f8\0\u0820\0\u0848"+
    "\0\u0870\0\u0898\0\u08c0\0\u08e8\0\u0230\0\u0910\0\u0938\0\u0960"+
    "\0\u0230\0\u0988\0\u09b0\0\u09d8\0\u0a00\0\u0a28\0\u0a50\0\u0500"+
    "\0\u0578\0\u0230\0\u05a0\0\u0618\0\u0a78\0\u0640\0\u06b8\0\u0230"+
    "\0\u0230\0\u0aa0\0\u0780\0\u0230\0\u07a8\0\u0ac8\0\u0230\0\u0af0"+
    "\0\u0b18\0\u0230\0\u0b40\0\u0b68\0\u0b90\0\u0bb8\0\u0be0\0\u0c08"+
    "\0\u0c30\0\u0c58\0\u0c80\0\u0ca8\0\u0cd0\0\u0cf8\0\u0d20\0\u0d48"+
    "\0\u0758\0\u0d70\0\u0d98\0\u0dc0\0\u0de8\0\u0230\0\u0230\0\u0e10"+
    "\0\u0e38\0\u0e60\0\u0e88\0\u0eb0\0\u0ed8\0\u0230\0\u0230\0\u0f00"+
    "\0\u0f28\0\u0f50\0\u0f78\0\u0fa0\0\u0fc8\0\u0ff0\0\u1018\0\u1040"+
    "\0\u1068\0\u1090\0\u10b8\0\u10e0\0\u1108\0\u1130\0\u1158\0\u0230"+
    "\0\u1180\0\u11a8\0\u0230\0\u0230\0\u11d0\0\u11f8\0\u1220\0\u1248"+
    "\0\u1270\0\u0230\0\u1298\0\u12c0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\5\1\1\14\6\1\1\15\1\1\1\16\31\1\1\17"+
    "\1\20\1\21\1\22\1\17\1\23\6\17\1\24\34\17"+
    "\1\20\1\21\1\22\1\17\1\25\7\17\1\26\32\17"+
    "\1\27\1\20\1\30\1\31\12\27\1\32\1\33\1\27"+
    "\1\34\2\27\1\35\1\36\2\27\1\37\3\27\1\40"+
    "\5\27\1\41\5\27\1\17\1\20\1\21\1\42\1\17"+
    "\1\43\1\44\10\17\1\45\1\17\15\44\4\17\5\44"+
    "\1\46\1\17\1\20\1\21\1\22\44\17\1\47\1\50"+
    "\1\51\1\52\13\47\1\53\30\47\1\54\1\55\1\56"+
    "\1\57\43\54\1\60\1\61\1\62\1\63\1\64\13\61"+
    "\1\65\30\61\1\17\1\20\1\21\1\66\1\67\1\70"+
    "\1\71\1\17\1\72\1\73\5\17\1\45\1\17\10\71"+
    "\1\74\4\71\1\17\1\75\1\76\1\77\5\71\2\17"+
    "\1\20\1\21\1\100\2\17\1\101\10\17\1\45\1\17"+
    "\16\101\3\17\6\101\5\1\1\14\1\0\5\1\1\15"+
    "\1\1\1\16\2\1\15\0\4\1\5\0\6\1\1\0"+
    "\6\1\1\15\1\1\1\16\36\1\1\14\6\1\1\15"+
    "\1\1\1\16\1\0\30\1\51\0\1\20\51\0\1\22"+
    "\52\0\1\102\12\0\15\102\4\0\5\102\7\0\1\103"+
    "\12\0\15\103\4\0\5\103\4\0\1\31\63\0\1\104"+
    "\50\0\1\105\51\0\1\106\52\0\1\107\53\0\1\110"+
    "\1\0\1\111\36\0\1\112\46\0\1\113\7\0\1\114"+
    "\61\0\1\115\7\0\1\42\52\0\1\44\12\0\15\44"+
    "\4\0\5\44\7\0\1\44\1\116\3\0\1\44\5\0"+
    "\15\44\4\0\5\44\50\0\1\117\17\120\1\121\31\120"+
    "\1\50\15\120\1\121\33\120\1\52\13\120\1\121\47\120"+
    "\1\121\1\122\27\120\47\123\1\124\1\123\1\55\45\123"+
    "\1\124\3\123\1\57\43\123\1\124\47\123\1\125\17\126"+
    "\1\127\31\126\1\62\15\126\1\127\33\126\1\64\13\126"+
    "\1\127\47\126\1\127\1\130\27\126\3\0\1\66\103\0"+
    "\1\131\16\0\1\71\12\0\15\71\4\0\5\71\7\0"+
    "\1\71\1\132\3\0\1\71\5\0\15\71\4\0\5\71"+
    "\1\0\10\133\1\134\37\133\11\135\1\134\36\135\6\0"+
    "\1\71\1\132\3\0\1\71\5\0\1\71\1\136\13\71"+
    "\4\0\5\71\41\0\1\137\50\0\1\137\11\0\1\100"+
    "\52\0\1\101\12\0\16\101\3\0\6\101\6\0\1\102"+
    "\1\140\3\0\1\102\5\0\15\102\4\0\5\102\7\0"+
    "\1\103\1\141\3\0\1\103\5\0\15\103\4\0\5\103"+
    "\27\0\1\142\20\0\1\143\22\0\1\144\53\0\1\145"+
    "\51\0\1\146\50\0\1\147\53\0\1\150\60\0\1\151"+
    "\36\0\1\152\20\0\1\153\1\0\2\154\7\0\15\153"+
    "\4\0\5\153\20\0\1\155\30\0\17\123\1\156\27\123"+
    "\1\125\6\0\1\157\1\0\2\160\7\0\15\157\4\0"+
    "\5\157\7\0\1\71\1\132\3\0\1\71\5\0\5\71"+
    "\1\161\7\71\4\0\5\71\7\0\1\162\1\0\2\163"+
    "\7\0\15\162\4\0\5\162\7\0\1\164\1\0\2\165"+
    "\7\0\15\164\4\0\5\164\50\0\1\166\23\0\1\167"+
    "\53\0\1\167\41\0\1\170\54\0\1\171\55\0\1\172"+
    "\51\0\1\173\45\0\1\174\21\0\1\153\1\0\2\175"+
    "\1\44\6\0\15\153\4\0\5\153\7\0\1\153\12\0"+
    "\15\153\4\0\5\153\21\0\1\176\27\0\20\123\1\177"+
    "\26\123\1\124\6\0\1\157\1\0\2\200\1\71\6\0"+
    "\15\157\4\0\5\157\7\0\1\157\12\0\15\157\4\0"+
    "\5\157\7\0\1\162\1\0\2\201\1\102\6\0\15\162"+
    "\4\0\5\162\7\0\1\162\12\0\15\162\4\0\5\162"+
    "\7\0\1\164\1\0\2\202\1\103\6\0\15\164\4\0"+
    "\5\164\7\0\1\164\12\0\15\164\4\0\5\164\46\0"+
    "\1\203\34\0\1\204\53\0\1\205\32\0\1\206\2\0"+
    "\1\207\1\210\2\0\1\211\55\0\1\212\23\0\1\44"+
    "\47\0\1\71\47\0\1\102\47\0\1\103\103\0\1\213"+
    "\23\0\1\214\52\0\1\215\44\0\1\216\52\0\1\217"+
    "\55\0\1\220\36\0\1\221\53\0\1\222\55\0\1\223"+
    "\34\0\1\167\61\0\1\224\36\0\1\225\53\0\1\226"+
    "\52\0\1\227\61\0\1\230\27\0\1\220\53\0\1\220"+
    "\46\0\1\231\65\0\1\232\35\0\1\233\37\0\1\234"+
    "\46\0\1\220\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4840];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\12\0\3\1\2\11\3\1\1\11\1\1\2\11"+
    "\55\1\1\11\3\0\1\11\10\0\1\11\5\0\2\11"+
    "\2\0\1\11\1\0\1\1\1\11\2\0\1\11\16\0"+
    "\1\1\4\0\2\11\2\0\1\1\3\0\2\11\20\0"+
    "\1\11\2\0\2\11\5\0\1\11\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[156];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Stack<Integer> stack = new Stack<Integer>();

    public void yypushState(int newState) {
      stack.push(yystate());
      yybegin(newState);
    }

 	public IElementType checkVariable(IElementType success, IElementType fail) {
        String matchedVar = yytext().toString();
        if (matchedVar.matches("(\\$[a-zA-Z]+)((\\((\\\"(?=[a-zA-Z]*\\\")|\\'(?=[a-zA-Z]*\\')|[a-zA-Z](?=[a-zA-Z]+))[a-zA-Z\\\"\\']+\\))|\\.[a-zA-Z]+)*")) {
           return success;
        }
        else {
           return fail;
        }
 	}

  	public IElementType checkBlockVariable(IElementType success, IElementType fail) {
        String matchedVar = yytext().toString();
        if (matchedVar.matches("(\\$?[a-zA-Z]+)((\\((\\\"(?=[a-zA-Z]*\\\")|\\'(?=[a-zA-Z]*\\')|[a-zA-Z](?=[a-zA-Z]+))[a-zA-Z\\\"\\']+\\))|\\.[a-zA-Z]+)*")) {
           return success;
        }
        else {
           return fail;
        }
 	}

    public void yypopState() {
      yybegin(stack.pop());
    }



  public SilverStripeLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public SilverStripeLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 120) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 19: 
          { yybegin(YYINITIAL); return SilverStripeTypes.SS_BLOCK_END;
          }
        case 35: break;
        case 6: 
          { yybegin(YYINITIAL); return SilverStripeTypes.SS_VAR_END_DELIMITER;
          }
        case 36: break;
        case 16: 
          { yybegin(YYINITIAL); return checkVariable(SilverStripeTypes.SS_VAR, SilverStripeTypes.SS_BAD_VAR);
          }
        case 37: break;
        case 25: 
          { yybegin(SS_TRANSLATION); return SilverStripeTypes.SS_BLOCK_START;
          }
        case 38: break;
        case 14: 
          { yybegin(SS_INCLUDE_STATEMENT); return TokenType.WHITE_SPACE;
          }
        case 39: break;
        case 26: 
          { yybegin(SS_COMMENT); return SilverStripeTypes.SS_COMMENT_START;
          }
        case 40: break;
        case 2: 
          { return TokenType.BAD_CHARACTER;
          }
        case 41: break;
        case 15: 
          { yybegin(SS_INCLUDE_STATEMENT); return SilverStripeTypes.SS_INCLUDE_FILE;
          }
        case 42: break;
        case 29: 
          { yybegin(YYINITIAL); return SilverStripeTypes.SS_COMMENT_END;
          }
        case 43: break;
        case 23: 
          { yybegin(SS_IF_STATEMENT); return SilverStripeTypes.SS_STRING;
          }
        case 44: break;
        case 1: 
          { if (yylength() > 0 && yytext().subSequence(yylength() - 1, yylength()).toString().equals("<")) {
            yypushback(1);
            yypushState(SS_BLOCK_START);
        }
        if (yylength() > 0 && yytext().subSequence(yylength() - 1, yylength()).toString().equals("$") ||
            yylength() > 0 && yytext().subSequence(yylength() - 1, yylength()).toString().equals("{") ) {
            yypushback(1);
            yybegin(SS_VAR);
        }

        // we stray from the Handlebars grammar a bit here since we need our WHITE_SPACE more clearly delineated
        //    and we need to avoid creating extra tokens for empty strings (makes the parser and formatter happier)
        if (!yytext().toString().equals("")) {
           if (yytext().toString().trim().length() == 0) {
               return TokenType.WHITE_SPACE;
           } else {
               return SilverStripeTypes.CONTENT;
           }
        }
          }
        case 45: break;
        case 11: 
          { yybegin(SS_IF_STATEMENT); return TokenType.WHITE_SPACE;
          }
        case 46: break;
        case 9: 
          { yybegin(SS_BLOCK_VAR); return TokenType.WHITE_SPACE;
          }
        case 47: break;
        case 30: 
          { yybegin(SS_BLOCK_VAR); yypushback(4); return SilverStripeTypes.COMMENT;
          }
        case 48: break;
        case 22: 
          { yybegin(SS_BLOCK_START); yypushback(2); return SilverStripeTypes.SS_TRANSLATION_CONTENT;
          }
        case 49: break;
        case 20: 
          { yybegin(SS_IF_STATEMENT); return SilverStripeTypes.SS_IF_KEYWORD;
          }
        case 50: break;
        case 8: 
          { yybegin(SS_BLOCK_START); return TokenType.WHITE_SPACE;
          }
        case 51: break;
        case 31: 
          { yybegin(SS_BLOCK_START); return SilverStripeTypes.SS_END_KEYWORD;
          }
        case 52: break;
        case 34: 
          { yybegin(SS_BLOCK_VAR); return SilverStripeTypes.SS_SIMPLE_KEYWORD;
          }
        case 53: break;
        case 27: 
          { yybegin(SS_BLOCK_VAR); return SilverStripeTypes.SS_START_KEYWORD;
          }
        case 54: break;
        case 24: 
          { yybegin(SS_IF_STATEMENT); return SilverStripeTypes.SS_AND_OR_OPERATOR;
          }
        case 55: break;
        case 3: 
          { yybegin(YYINITIAL); return SilverStripeTypes.CRLF;
          }
        case 56: break;
        case 28: 
          { yybegin(SS_BLOCK_START); return SilverStripeTypes.SS_ELSE_KEYWORD;
          }
        case 57: break;
        case 21: 
          { yybegin(SS_BLOCK_VAR); yypushback(2); return SilverStripeTypes.SS_BAD_BLOCK_STATEMENT;
          }
        case 58: break;
        case 12: 
          { yybegin(SS_IF_STATEMENT); return checkBlockVariable(SilverStripeTypes.SS_BLOCK_VAR, SilverStripeTypes.SS_BAD_VAR);
          }
        case 59: break;
        case 33: 
          { yybegin(SS_IF_STATEMENT); return SilverStripeTypes.SS_ELSE_IF_KEYWORD;
          }
        case 60: break;
        case 18: 
          { yybegin(SS_BLOCK_START); return SilverStripeTypes.SS_BLOCK_START;
          }
        case 61: break;
        case 5: 
          { yybegin(SS_WITH_DELIMITER); return SilverStripeTypes.SS_VAR_START_DELIMITER;
          }
        case 62: break;
        case 4: 
          { yybegin(YYINITIAL); return TokenType.WHITE_SPACE;
          }
        case 63: break;
        case 17: 
          { yybegin(SS_WITH_DELIMITER); return checkVariable(SilverStripeTypes.SS_VAR, SilverStripeTypes.SS_BAD_VAR);
          }
        case 64: break;
        case 32: 
          { yybegin(SS_INCLUDE_STATEMENT); return SilverStripeTypes.SS_INCLUDE_KEYWORD;
          }
        case 65: break;
        case 10: 
          { yybegin(SS_BLOCK_VAR); return checkBlockVariable(SilverStripeTypes.SS_BLOCK_VAR, SilverStripeTypes.SS_BAD_VAR);
          }
        case 66: break;
        case 7: 
          { yybegin(SS_BAD_BLOCK_STATEMENT); yypushback(1);
          }
        case 67: break;
        case 13: 
          { yybegin(SS_IF_STATEMENT); return SilverStripeTypes.SS_COMPARISON_OPERATOR;
          }
        case 68: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
